### ISSUE TITLE
Don't try to parse response body unless it's JSON

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-client-web#12]
Lots of services respond with a 204 status, which doesn't even have a body.

This is causing issues with the purge-cache service for example.

**Comment by eliperelman** [comment]
Do we get a different response type in those instances, or should we directly check for 204?

**Comment by djmitche** [comment]
I'm not sure if the Content-Type is set incorrectly, or what, if that's what you mean.

**Comment by eliperelman** [comment]
Yeah, that's all I was wondering was if it still used `application/json`.

**Comment by djmitche** [comment]
![screenshot from 2017-09-25 11-54-46](https://user-images.githubusercontent.com/28673/30818001-607c5618-a1e8-11e7-9f53-97c4b3381c81.png)

Looks like no, no content-type.  And an empty body.  But I still got "Error executing operation: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" in the purge-caches tool.
