### ISSUE TITLE
Update to Hawk 7

### ISSUE THREAD

**Issue by edmorley** [taskcluster/taskcluster-client-web#22]
Currently taskcluster-client-web is using Hawk 6 (the same as taskcluster-client), meaning that anyone who uses latest Hawk themselves (and so has a first-party dependency on Hawk 7) will end up bundling two versions of Hawk to their browser users.

There are a few breaking changes in Hawk 7, but the API is now much improved IMO :-)

See:
https://github.com/hueniverse/hawk/commit/f72cdeafd178bbd893e8c041510f2ecd733c0011

**Comment by djmitche** [comment]
Same as https://bugzilla.mozilla.org/show_bug.cgi?id=1426403
